ERROR: Main Menu and Freq Game now work (except switch between freq and amp)
Small issue where the Switch between amp and freq is called twice thus resulting in not switching modes, also it somehow gets set to amp even though I never set it that way

The problem is somewhere in the unity code since the arduino script is working as intended